version: "3.2"
services:
  elasticsearch-master:
    image: elasticsearch:${ES_VERSION}
    restart: always
    container_name: elasticsearch-master
    hostname: elasticsearch-master
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - node.name=elasticsearch-master
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/efk/elasticsearch-master/data:/usr/share/elasticsearch/data
      - ~/efk/elasticsearch-master/logs:/usr/share/elasticsearch/logs
      - ~/efk/elasticsearch/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    extra_hosts:
      - 'elasticsearch-master: ${MASTER_IP}'
    networks:
      - outside
  elasticsearch1:
    image: elasticsearch:${ES_VERSION}
    restart: always
    container_name: elasticsearch1
    hostname: elasticsearch1
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - node.name=elasticsearch1
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/efk/elasticsearch1/data:/usr/share/elasticsearch/data
      - ~/efk/elasticsearch1/logs:/usr/share/elasticsearch/logs
      - ~/efk/elasticsearch/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    extra_hosts:
      - 'elasticsearch: ${MASTER_IP}'
    networks:
      - outside
  elasticsearch2:
    image: elasticsearch:${ES_VERSION}
    restart: always
    container_name: elasticsearch2
    hostname: elasticsearch2
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - node.name=elasticsearch2
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/efk/elasticsearch2/data:/usr/share/elasticsearch/data
      - ~/efk/elasticsearch2/logs:/usr/share/elasticsearch/logs
      - ~/efk/elasticsearch/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    extra_hosts:
      - 'elasticsearch: ${MASTER_IP}'
    networks:
      - outside
networks:
  outside:
    external:
      name: efk