version: "3.2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    restart: always
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - cluster.name=boss-elasticsearch
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
      - node.data=true
      - discovery.zen.ping.unicast.hosts.resolve_timeout=1d
      - discovery.zen.ping.unicast.hosts=${MASTER_IP}:${MASTER_PORT}
      - discovery.zen.minimum_master_nodes=1
      - path.data=/usr/share/elasticsearch/data
      - path.logs=/usr/share/elasticsearch/logs
      - node.name=${NODE_NAME}
      - transport.publish_host=${THIS_IP}
      - transport.publish_port=${THIS_PORT}
      - node.master=${IS_MASTER}
    ports:
      - ${THIS_HTTP_PORT}:9200
      - ${THIS_PORT}:9300
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/bosselastic/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/bosselastic/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ~/bosselastic/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    networks:
      - outside
  searchhead:
    image: docker.elastic.co/mobz/elasticsearch-head:5
    restart: always
    container_name: searchhead
    hostname: searchhead
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 9100:9100
    networks:
      - outside
networks:
  outside:
    external:
      name: efk