version: "3.2"
services:
  elasticsearch0:
    image: elasticsearch:7.10.1
    restart: always
    container_name: elasticsearch0
    hostname: elasticsearch0
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - node.name=elasticsearch0
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/efk/elasticsearch0/:/usr/share/elasticsearch/
      - ~/efk/elasticsearch/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    extra_hosts:
      - 'elasticsearch: ${THIS_IP}:9301'
    networks:
      - outside
  elasticsearch1:
    image: elasticsearch:7.10.1
    restart: always
    container_name: elasticsearch1
    hostname: elasticsearch1
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - node.name=elasticsearch1
    volumes:
      - /etc/localtime:/etc/localtime
      - ~/efk/elasticsearch1/:/usr/share/elasticsearch/
      - ~/efk/elasticsearch/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    extra_hosts:
      - 'elasticsearch: ${THIS_IP}:9301'
    networks:
      - outside
networks:
  outside:
    external:
      name: efk